---
title: "outliers"
author: "Paris.N"
date: "11/30/2021"
output: html_document
---
Exclusion Criteria:
subjects were excluded if:
1 - their accuracy was bellow than 50%.
2 - they missed more than 20% of trials in a task
3 - after doing task, they claimed that they didn't understand the task 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(R.matlab)
```

```{r}
#1- find subjects' accuracy which is less than 0.5
# first run the regression file
pool_acc <-c(unlist(accuracy), unlist(accuracy_O))
acc_dat <- data.frame(
  id = rep(1:38, 2),
  acc =pool_acc,
  beneficiary = as.factor(rep(c("self" , "other"), each = 38))
)
acc_dat
ggplot2::ggplot(acc_dat, aes(x = beneficiary, y = acc, fill = forcats::fct_rev (beneficiary))) +
  geom_boxplot() +
  labs(x = "beneficiary", y = "accuracy", fill = "") +
  theme_minimal(base_size = 21)
```

```{r}
# 2 - find subjects with more than 25 missing trials (20%) 

num_subjects <-  38
num_trials <- 126
preSelf <-  "my_data/subject_"
preOther <- "my_data/subjectO_"
index_data <- data.frame(id = integer(),
                         missing_choices = double(),
                         beneficiary = character()
)
index_data_O <- data.frame(id = integer(),
                         missing_choices = double(),
                         beneficiary = character()
)

for(n in 1:num_subjects){
  miss_ch <- 0
  miss_ch_O <- 0
  #dir_self
  dirSelf <-  paste(preSelf,n,"/data.mat",sep="")
  dirOther <- paste(preOther,n,"/data.mat",sep="")
  subject <-  readMat(dirSelf)
  subject_O <-  readMat(dirOther)
  #choice_self
  ch <- subject$data[,,1]$choice
  ch_O <- subject_O$data[,,1]$choice
  for (z in 1: num_trials){
    if (ch[z] == 0){
      miss_ch = miss_ch + 1
    }
    if (ch_O[z] == 0){
      miss_ch_O = miss_ch_O + 1
    }
  }
  this_sub <- data.frame(id = n,
                         missing_choices = miss_ch,
                         beneficiary = "self")
  this_sub_O <- data.frame(id = n,
                         missing_choices = miss_ch_O,
                         beneficiary = "other")
  index_data[nrow(index_data) + 1, ] <- this_sub
  index_data_O[nrow(index_data_O) + 1, ] <- this_sub_O
}
index_data
index_data_O
my_data <- rbind(index_data, index_data_O)
```

```{r}
ggplot2::ggplot(my_data, aes(x = beneficiary, y = missing_choices, fill = forcats::fct_rev (beneficiary))) +
  geom_boxplot() +
  labs(x = "beneficiary", y = "missing_choices", fill = "") +
  theme_minimal(base_size = 21)
```

```{r}
# pic place -------------------------------------------------------------- self
right <- list()
left <- list()
max_r <- list()
max_l <- list()
for(n in 1:num_subjects){
  max_right <- 0
  max_left <- 0
  pic_l <- 0
  pic_r <- 0
  max_att <- list()
  #dir_self
  dirSelf <-  paste(preSelf,n,"/data.mat",sep="")
  dirOther <- paste(preOther,n,"/data.mat",sep="")
  subject <-  readMat(dirSelf)
  subject_O <-  readMat(dirOther)
  #choice self
  ch <- subject$data[, , 1]$choice
  ind_choice <- which(ch!=0)
  choice <- ch[ind_choice]
  len <- length(choice)
  #reward self
  rew <- subject$data[, , 1]$reward
  reward <- rew[ind_choice]
  #reward probs
  reward_probs <- subject$data[, , 1]$rewardProbs
  first_column  <-  reward_probs[ind_choice,,1][,1]
  second_column  <-  reward_probs[ind_choice,,2][,1]
  
  pic_pl <- subject$data[, , 1]$pic.place
  pic_pl <- pic_pl[ind_choice]
  for (z in 1: len){
    if(first_column[z] >= second_column[z]){
      max_rew = first_column[z]
    }
    else{
      max_rew = second_column[z]
    }
    if (pic_pl[z] == 0){
      pic_r = pic_r + 1
    }
    else if (pic_pl[z] == 1){
      pic_l = pic_l + 1
    }
    if(pic_pl[z] == 0 & reward[z] == max_rew){
      max_right = max_right + 1
    }
    if(pic_pl[z] == 0 & reward[z] != max_rew){
      max_left = max_left + 1
    }
    if (pic_pl[z] == 1 & reward[z] == max_rew){
      max_left = max_left + 1
    }
    if (pic_pl[z] == 1 & reward[z] != max_rew){
      max_right = max_right + 1 
    }
    max_att[z] <- max_rew
  }
  right[n] <- pic_r
  left[n] <- pic_l
  max_r[n] <- max_right
  max_l[n] <- max_left
  
}
ratio_right <- unlist(right) / unlist(max_r)
ratio_left <- unlist(left) / unlist(max_l)
side_dat <- data.frame( id = c(1:num_subjects),
                        pic_right = unlist(right),
                        max_right = unlist(max_r),
                        pic_left = unlist(left),
                        max_left = unlist(max_l))
hist(unlist(max_left))
ggplot2::ggplot(side_dat, aes(pic_right)) +
  geom_histogram(binwidth = 5, fill = "#56B4E9", alpha = 0.5) +
  labs(y = "Frequency", x = "Days since first ice bucket challenge video") +
  theme_minimal()
```

```{r}
# pic place -------------------------------------------------------------- other
right_O <- list()
left_O <- list()
max_r_O <- list()
max_l_O <- list()
for(n in 1:num_subjects){
  max_right_O <- 0
  max_left_O <- 0
  pic_l_O <- 0
  pic_r_O <- 0
  max_att_O <- list()
  #dir_self
  dirOther <- paste(preOther,n,"/data.mat",sep="")
  subject_O <-  readMat(dirOther)
  #choice self
  ch <- subject_O$data[, , 1]$choice
  ind_choice <- which(ch!=0)
  choice <- ch[ind_choice]
  len <- length(choice)
  #reward self
  rew <- subject_O$data[, , 1]$reward
  reward <- rew[ind_choice]
  #reward probs
  reward_probs <- subject_O$data[, , 1]$rewardProbs
  first_column  <-  reward_probs[ind_choice,,1][,1]
  second_column  <-  reward_probs[ind_choice,,2][,1]
  
  max_att_O <- subject_O$data[, , 1]$pic.place
  max_att_O <- max_att_O[ind_choice]
  for (z in 1: len){
    if(first_column[z] >= second_column[z]){
      max_rew = first_column[z]
    }
    else{
      max_rew = second_column[z]
    }
    if (max_att_O[z] == 0){
      pic_r_O = pic_r_O + 1
    }
    else if (max_att_O[z] == 1){
      pic_l_O = pic_l_O + 1
    }
    if(max_att_O[z] == 0 & reward[z] == max_rew){
      max_right_O = max_right_O + 1
    }
    if(max_att_O[z] == 0 & reward[z] != max_rew){
      max_left_O = max_left_O + 1
    }
    if (max_att_O[z] == 1 & reward[z] == max_rew){
      max_left_O = max_left_O + 1
    }
    if (max_att_O[z] == 1 & reward[z] != max_rew){
      max_right_O = max_right_O + 1 
    }
    max_att_O[z] <- max_rew
  }
  right_O[n] <- pic_r_O
  left_O[n] <- pic_l_O
  max_r_O[n] <- max_right_O
  max_l_O[n] <- max_left_O
  
}
ratio_right_O <- unlist(right_O) / unlist(max_r_O)
ratio_left_O <- unlist(left_O) / unlist(max_l_O)
side_dat_O <- data.frame( id = c(1:num_subjects),
                        pic_right_O = unlist(right_O),
                        max_right_O = unlist(max_r_O),
                        pic_l_left_O = unlist(left_O),
                        max_left_O = unlist(max_l_O))
hist(unlist(max_left_O))
ggplot2::ggplot(side_dat_O, aes(pic_right_O)) +
  geom_histogram(binwidth = 5, fill = "#56B4E9", alpha = 0.5) +
  labs(y = "Frequency", x = "Days since first ice bucket challenge video") +
  theme_minimal()

```

